check if latest ver is already published

diff --git a/kumk b/kumk
--- a/kumk
+++ b/kumk
@@ -6,7 +6,7 @@ set -e
 
 VERSION="0.6.11"
 
-URL=https://kernel.ubuntu.com/~kernel-ppa/mainline/
+URL="https://kernel.ubuntu.com/~kernel-ppa/mainline"
 DATA=/tmp/kumk
 [[ ! $2 = *lowlattency* ]] && MODE="generic" ||  MODE="lowlattency"
 TMP="${DATA}/tmp"
@@ -51,9 +51,12 @@ set_locale(){
             help_free_on="Volno v"
 
             this_version_have_failed_build="Tato verze obsahuje neůspěšný build... Končím..."
+            kernel_is_not_ready_yet="(zatím v přípravě)"
+            this_version_not_ready_yet_switch_to_previous_yes_no="poslední jádro ${VER} zatím není připraveno, přepnout na předposlední ${VER_PREV}? [a/N] "
             downloading_ver="Stahuji ${VER}..."
             packages_for_ver_not_found_exiting="Balíček pro ${VER} nenalezen... Končím..."
             download_file_deb="Stahuji soubor: ${deb}..."
+            download_file_deb_failed="Nepodařílo se stáhnout soubor: ${deb}... Končím..."
             in_system_is_installed_libc_ge_req_installing_normal="v systému je nainstalována libc >=${libc6_req}, instaluji normálně..."
             install_ver_yes_no="Instalovat ${VER}? [a/N] "
             installing_kernel_version_gt_51116_and_libc6_is_lt_req_install_via_workaround="instalovaná verze jádra je >5.11.16 a libc6 je <${libc6_req}, instaluju workaroundem..."
@@ -103,9 +106,12 @@ set_locale(){
             help_free_on="Free on"
 
             this_version_have_failed_build="This version have failed build. Exiting..."
+            kernel_is_not_ready_yet="(not ready yet)"
+            this_version_not_ready_yet_switch_to_previous_yes_no="latest kernel ${VER} not ready yet, switch to previous latest ${VER_PREV}? [y/N] "
             downloading_ver="Downloading ${VER}..."
             packages_for_ver_not_found_exiting="Packages for ${VER} not found... Exiting..."
             download_file_deb="Downloading file: ${deb}..."
+            download_file_deb_failed="Downloading file: ${deb} failed... Exiting..."
             in_system_is_installed_libc_ge_req_installing_normal="in system is installed libc >=${libc6_req}, installing normal..."
             install_ver_yes_no="Install ${VER}? [y/N] "
             installing_kernel_version_gt_51116_and_libc6_is_lt_req_install_via_workaround="installing kernel version >5.11.16 and libc6 is <${libc6_req}, installing via workaround..."
@@ -189,9 +195,23 @@ detect_arch(){
 }
 
 download_kernel(){
+    ver_check_success="$(wget -q "${URL}/v${VER}/HEADER.html" -O- | grep "${ARCH}/build succeeded" || true)"
+    [[ ${ver_check_success} ]] || {
+        set_locale
+        ewarnn "${this_version_not_ready_yet_switch_to_previous_yes_no}"
+        read -n1 answer; echo ""
+        [[ "${answer}" = [y,Y,a,A] ]] && {
+            VER="${VER_PREV}"
+            set_locale
+        } || {
+            ewarn "${install_canceled}"
+            exit
+        }
+    }
+
     mkdir -p ${TMP}
     header="${TMP}/${VER}-HEADER.html"
-    wget -q ${URL}/v${VER}/HEADER.html -O ${header}
+    wget -q "${URL}/v${VER}/HEADER.html" -O ${header}
 
     if (grep -q -e "Build for ${ARCH} failed" -e "Test ${ARCH}/build failed" ${header}); then
         eerror "${this_version_have_failed_build}"
@@ -203,7 +223,10 @@ download_kernel(){
         for deb in ${debs[@]}; do
             set_locale
             ewarn "${download_file_deb}"
-            wget -q --continue --no-verbose --directory-prefix ${DATA}/${VER} ${URL}/v${VER}/${deb}
+            wget -q --continue --no-verbose --directory-prefix ${DATA}/${VER} "${URL}/v${VER}/${deb}" || {
+                eerror "${download_file_deb_failed}"
+                exit
+            }
         done
     fi
 }
@@ -325,8 +348,20 @@ purge_kernel(){
 }
 
 show_versions(){
-    is_available="$(wget -q "https://kernel.ubuntu.com/~kernel-ppa/mainline" -O- | grep ">v5" | sed 's/.*>v5/5/;s/\/<.*//' | sort --version-sort)"
-    [[ $2 = norc || $1 = norc ]] && is_available="$(echo "${is_available}" | grep -v rc)"
+    is_available="$(wget -q "${URL}" -O- | grep ">v5" | sed 's/.*>v5/5/;s/\/<.*//' | sort --version-sort)"
+
+    last_norc="$(echo "${is_available}" | grep -v rc | tail -n1)"
+    last_norc_check_success="$(wget -q "${URL}/v${last_norc}/HEADER.html" -O- | grep "${ARCH}/build succeeded" || true)"
+    [[ ${last_norc_check_success} ]] || is_available="$(echo "${is_available}" | sed "s/^${last_norc}$/& ${kernel_is_not_ready_yet}/")"
+
+    [[ $2 = norc || $1 = norc ]] && { 
+        is_available="$(echo "${is_available}" | grep -v rc)" 
+    } || {
+        last_rc="$(echo "${is_available}" | tail -n1)"
+        last_rc_check_success="$(wget -q "${URL}/v${last_rc}/HEADER.html" -O- | grep "${ARCH}/build succeeded" || true)"
+        [[ ${last_rc_check_success} ]] || is_available="$(echo "${is_available}" | sed "s/^${last_rc}$/& ${kernel_is_not_ready_yet}/")"
+    }
+
     [[ $1 ]] && echo "${is_available}" | grep ^${1} ||  echo "${is_available}"
     exit 0
 }
@@ -395,9 +430,13 @@ elif [[ "$2" = "" && "$1" != @(s|show) && "$1" != "" && "$1" != @(l|list) ]]; th
     eerror "${error_must_enter_version_as_second_parameter}"
     exit
 elif [[ "$2" = "latest" && "$1" != @(s|show) ]]; then
-    VER="$(show_versions | grep -v rc | tail -n1 | sed 's/^v//')"
+    tmp_ver="$(show_versions | grep -v rc | tail -n2 | sed 's/^v//;s/ (.*//')"
+    VER="$(echo "${tmp_ver}" | tail -n1)"
+    VER_PREV="$(echo "${tmp_ver}" | head -n1)"
 elif [[ "$2" = "latest-rc" && "$1" != @(s|show) ]]; then
-    VER="$(show_versions | tail -n1 | sed 's/^v//')"
+    tmp_ver="$(show_versions | tail -n2 | sed 's/^v//;s/ (.*//')"
+    VER="$(echo "${tmp_ver}" | tail -n1)"
+    VER_PREV="$(echo "${tmp_ver}" | head -n1)"
 elif [[ "$1" != @(s|show) ]]; then
     VER="$(echo ${2} | sed 's/-generic//;s/-lowlattency//;s/*//g')"
 fi
